config/routes.rb
Rails.application.routes.draw do

  root "projects#index"
  
  resources :projects do 
    resources :tasks
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discussion



  validates :topic, presence: true, uniqueness: true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  has_many :comments, dependent: :destroy


  validates :topic, presence: true, uniqueness: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  validates :title, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
# encoding: UTF-8
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  after_filter :flash_to_headers

  private

    def flash_to_headers
      return unless request.xhr?
      msg = flash_message
      #replace german umlaute encoded in utf-8 to html escaped ones
      msg = msg.gsub("ä","&auml;").gsub("ü","&uuml;").gsub("ö","&ouml;").gsub("Ä","&Auml;").gsub("Ü","&Uuml;").gsub("Ö","&Ouml;").gsub("ß","&szlig;")
      response.headers['X-Message'] = msg
      response.headers["X-Message-Type"] = flash_type.to_s

      flash.discard # don't want the flash to appear when you reload page
    end

    def flash_message
      [:error, :warning, :notice].each do |type|
        return flash[type] unless flash[type].blank?
      end
      # if we don't return something here, the above code will return "error, warning, notice"
      return ''
    end

    def flash_type
      #:keep will instruct the js to not update or remove the shown message.
      #just write flash[:keep] = true (or any other value) in your controller code
      [:error, :warning, :notice, :keep].each do |type|
        return type unless flash[type].blank?
      end
      #don't return the array from above which would happen if we don't have an explicit return statement
      #returning :empty will also allow you to easily know that no flash message was transmitted
      return :empty
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :get_project, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all 
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      respond_to do |format|
        format.js
      end
    else
      flash[:warning] = "The project title cannot be blank!"
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    @project.update_attributes(project_params)
    respond_to do |format|
      format.js
    end
  end


  private
  def get_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :due_date)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_project
  before_action :find_task, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)
    @task.save

    if @task.save
      respond_to do |format|
        format.js
      end

    else
      flash[:warning] = "You tried to create a task that had nothing."
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.js
    end
  end

  def edit
  end

  def update
    if @task.update_attributes(task_params)
      respond_to do |format|
        format.js
      end
    else
      flash[:warning] = "The content cannot be blank"
      respond_to do |format|
        format.js
      end
    end
  end



private
def find_project
  @project = Project.find(params[:project_id])
end

def find_task
  @task = @project.tasks.find(params[:id])
end

def task_params
  params.require(:task).permit(:title, :due_date)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheUltimatePm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <ul class="nav nav-tabs" role="tablist">
    <li><%= link_to "Project", projects_path %></li>
  </ul>
  <%= yield %>
</div>
</body>
</html>

app/views/projects/_create.html.erb
<div id="project_toggle">
  <%= form_for(Project.new, remote: true, :html => {id: "project_create_form"}) do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control", id: "project_title_field", remote: true %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.submit class: "btn btn-default" %>
    </div>
  <% end %>

app/views/projects/_project.html.erb
<div class= "panel panel-info" id="<%= dom_id(project)%>">
  <div class="panel-heading" id="project_title">
    <%= project.title %>
  </div>
  <div class="panel-body" id="project_description">
    <%= project.description %>
  </div>
  <div class="panel-footer">
    <%= link_to "Details", project_tasks_path(project), class: "btn btn-primary" %>
    <%= link_to "Edit", edit_project_path(project), class: "btn btn-success", remote: true %>
    <%= link_to "Destroy", project, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger", remote: true %>
  </div>
</div>

app/views/projects/_update.html.erb
<div id= "project_update_form" >
  <%= form_for(@project, remote: true) do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control", id:"update_title" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit class: "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/projects/create.js.erb
<% if @project.new_record? %>
  $("#project_title_field").effect("highlight", {color:"red"});
<% else %>
  $("div#projects").append("<%= escape_javascript(render @project) %>");
  $("div#<%= dom_id(@project) %>").effect("highlight"); 
  $("#project_create_form")[0].reset();
  $("a#project_form_toggle").click();
<% end %>

app/views/projects/destroy.js.erb
$("#<%= dom_id(@project) %>").fadeOut();

app/views/projects/edit.js.erb
$("#<%= dom_id(@project) %>").append("<%= escape_javascript(render 'update') %>");

app/views/projects/index.html.erb
<div class="jumbotron">
  <h2>Project List</h2>
</div>

<br/>

<div id="projects">
  <%= render @projects %>
</div>

<br />
<br />

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" id="project_form_toggle">
          Creat a project
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render "create" %>
      </div>
    </div>
  </div>

app/views/projects/update.js.erb
<% if !@project.save %>

  $("#update_title").effect("highlight", {color: "red"});

<% else %>

  $("div#<%= dom_id(@project)%> #project_title").text("<%= @project.title %>").effect("highlight", {}, 2000)
  $("div#<%= dom_id(@project)%> #project_description").text("<%= @project.description %>").effect("highlight", {}, 2000)
  $("div#project_update_form").fadeOut();

<% end %>

app/views/tasks/_create.html.erb
<%= form_for([@project, Task.new], remote: true, :html => {id:"task_create_form"}) do |f| %>
  <div class="form-group">
    <%= f.text_area :title, class: "form-control", id: "task_title_field", remote: true %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class= "panel panel-info" id="<%= dom_id(task)%>">
  <div class="panel-heading" id="task_title">
    <%= task.title %>
  </div>
  <div class="panel-footer">
    <div class = "btn-group btn-group-sm">
      <%= link_to "Edit", edit_project_task_path(@project, task), remote: true, class: "btn btn-success" %>
      <%= link_to "Destroy", [@project, task], method: :delete, data: {confirm: "Are you sure?"}, class: "btn-group-sm btn btn-danger", remote: true %>
    </div>
  </div>
</div>

app/views/tasks/_update.html.erb
<div id="task_udpate_form">
  <%= form_for([@project, @task], remote: true) do |f| %>
    <div class="form-group">
      <%= f.text_area :title, class: "form-control", id: "task_title_update_field", remote: true %>

    <div class="form-group">
      <%= f.submit class: "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/tasks/create.js.erb
<% if @task.new_record? %>
  $("#task_title_field").effect("highlight", {color:"red"});
<% else %>
  $("div#tasks").append("<%= escape_javascript(render @task) %>");
  $("div#<%= dom_id(@task) %>").effect("highlight");
  $("#task_create_form")[0].reset();
<% end %>

app/views/tasks/destroy.js.erb
$("#<%= dom_id(@task) %>").fadeOut();

app/views/tasks/edit.js.erb
$("#<%= dom_id(@task)%>").append("<%= escape_javascript(render 'update') %>");

app/views/tasks/index.html.erb
<div class="jumbotron" id="project_detail">
  <h2><%= @project.title %></h2>
  <p><%= @project.description %></p>
</div>

<div class="panel-group" id="accordion2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Add a task
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render "create" %>
      </div>
    </div>
  </div>

  <br/>
  <div id="tasks">
    <%= render @project.tasks %>
  </div>

app/views/tasks/update.js.erb
<% if !@task.save %>
  $("#task_title_update_field").effect("highlight", {color: "red"});

<% else %>
  
  $("div#<%= dom_id(@task) %> #task_title").text("<%= @task.title %>").effect("highlight", {}, 2000);
  $("div#task_udpate_form").fadeOut();

<% end %>